package e

var MsgFlags = map[int]string{
	SUCCESS:        "ok",
	ERROR:          "fail",
	INVALID_PARAMS: "请求参数错误",
	UNAUTHORIZED:   "没有访问权限",

	ERROR_EDIT_USER_FAIL:              "编辑用户失败",
	ERROR_NOT_EXIST_USER:              "用户不存在",
	ERROR_GET_USER_FAIL:               "获取用户失败",
	ERROR_GET_ALL_USER_FAIL:           "获取所有用户失败",
	ERROR_CLEAN_SOFT_DELETE_USER_FAIL: "清空所有软删除用户失败",
	ERROR_ADD_USER_FAIL:               "添加用户失败",
	ERROR_DELETE_USER_FAIL:            "删除用户失败",
	ERROR_CHECK_EXIST_USER_FAIL:       "验证已存在用户失败",
	ERROR_COUNT_USER_FAIL:             "统计用户数量失败",
	ERROR_CHECK_PASSWORD_FAIL:         "验证密码失败",
	ERROR_USER_NAME_OR_PASSWORD:       "用户名或者密码错误",
	ERROR_EXIST_USER_NAME:             "用户名已存在",
	ERROR_RESET_PASSWORD_FAIL:         "修改密码失败",
	ERROR_PASSWORD_SIZE:               "密码长度不能小于6位",

	ERROR_NOT_EXIST_API:        "不存在",
	ERROR_GET_API_FAIL:         "获取失败",
	ERROR_GET_ALL_API_FAIL:     "获取所有失败",
	ERROR_CHECK_EXIST_API_FAIL: "验证已存在失败",
	ERROR_COUNT_API_FAIL:       "统计数量失败",

	ERROR_REPEAT_LUCKY:        "正在抽奖，请稍后重试",
	ERROR_DAY_NOT_LUCKY_COUNT: "今日抽奖次数已用完",

	ERROR_CHECK_TOKEN_FAIL:  "Token鉴权失败",
	ERROR_TOKEN_TIMEOUT:     "Token已超时",
	ERROR_CREATE_TOKEN_FAIL: "Token生成失败",
	ERROR_TOKEN:             "Token错误",
	ERROR_PARSE_TOKEN_FAIL:  "Token解析失败",

	ERROR_UPLOAD_SAVE_IMAGE_FAIL:    "保存图片失败",
	ERROR_UPLOAD_CHECK_IMAGE_FAIL:   "检查图片失败",
	ERROR_UPLOAD_CHECK_IMAGE_FORMAT: "校验图片错误，图片格式或大小有问题",

	ERROR_GET_CAPTCHA_FAIL: "生成图形验证码失败",
	ERROR_CAPTCHA:          "图形验证码错误",

	ERROR_GET_ROLE_FAIL: "获取角色信息失败",

	ERROR_CREATE_VERIFY_CODE_FAIL: "验证码生成失败",
	ERROR_VERIFY_CODE:             "验证码错误",
	ERROR_VERIFY_CODE_TIMEOUT:     "验证码超时",
	ERROR_CHECK_VERIFY_CODE_FAIL:  "校验验证码失败",

	ERROR_EDIT_PRODUCT_FAIL:              "编辑商品失败",
	ERROR_NOT_EXIST_PRODUCT:              "商品不存在",
	ERROR_GET_PRODUCT_FAIL:               "获取商品失败",
	ERROR_GET_ALL_PRODUCT_FAIL:           "获取所有商品失败",
	ERROR_CLEAN_SOFT_DELETE_PRODUCT_FAIL: "清空所有软删除商品失败",
	ERROR_ADD_PRODUCT_FAIL:               "添加商品失败",
	ERROR_DELETE_PRODUCT_FAIL:            "删除商品失败",
	ERROR_CHECK_EXIST_PRODUCT_FAIL:       "验证已存在商品失败",
	ERROR_COUNT_PRODUCT_FAIL:             "统计商品数量失败",

	ERROR_EDIT_CATEGORY_FAIL:              "编辑商品分类失败",
	ERROR_NOT_EXIST_CATEGORY:              "商品分类不存在",
	ERROR_GET_CATEGORY_FAIL:               "获取商品分类失败",
	ERROR_GET_ALL_CATEGORY_FAIL:           "获取所有商品分类失败",
	ERROR_CLEAN_SOFT_DELETE_CATEGORY_FAIL: "清空所有软删除商品分类失败",
	ERROR_ADD_CATEGORY_FAIL:               "添加商品分类失败",
	ERROR_DELETE_CATEGORY_FAIL:            "删除商品分类失败",
	ERROR_CHECK_EXIST_CATEGORY_FAIL:       "验证已存在商品分类失败",
	ERROR_COUNT_CATEGORY_FAIL:             "统计商品分类数量失败",

	ERROR_EDIT_AD_FAIL:              "编辑广告失败",
	ERROR_NOT_EXIST_AD:              "广告不存在",
	ERROR_GET_AD_FAIL:               "获取广告失败",
	ERROR_GET_ALL_AD_FAIL:           "获取所有广告失败",
	ERROR_CLEAN_SOFT_DELETE_AD_FAIL: "清空所有软删除广告失败",
	ERROR_ADD_AD_FAIL:               "添加广告失败",
	ERROR_DELETE_AD_FAIL:            "删除广告失败",
	ERROR_CHECK_EXIST_AD_FAIL:       "验证已存在广告失败",
	ERROR_COUNT_AD_FAIL:             "统计广告数量失败",

	ERROR_EDIT_BRAND_FAIL:              "编辑品牌失败",
	ERROR_NOT_EXIST_BRAND:              "品牌不存在",
	ERROR_GET_BRAND_FAIL:               "获取品牌失败",
	ERROR_GET_ALL_BRAND_FAIL:           "获取所有品牌失败",
	ERROR_CLEAN_SOFT_DELETE_BRAND_FAIL: "清空所有软删除品牌失败",
	ERROR_ADD_BRAND_FAIL:               "添加品牌失败",
	ERROR_DELETE_BRAND_FAIL:            "删除品牌失败",
	ERROR_CHECK_EXIST_BRAND_FAIL:       "验证已存在品牌失败",
	ERROR_COUNT_BRAND_FAIL:             "统计品牌数量失败",

	ERROR_EDIT_INDEX_BANNER_FAIL:              "编辑首页轮播图失败",
	ERROR_NOT_EXIST_INDEX_BANNER:              "首页轮播图不存在",
	ERROR_GET_INDEX_BANNER_FAIL:               "获取首页轮播图失败",
	ERROR_GET_ALL_INDEX_BANNER_FAIL:           "获取所有首页轮播图失败",
	ERROR_CLEAN_SOFT_DELETE_INDEX_BANNER_FAIL: "清空所有软删除首页轮播图失败",
	ERROR_ADD_INDEX_BANNER_FAIL:               "添加首页轮播图失败",
	ERROR_DELETE_INDEX_BANNER_FAIL:            "删除首页轮播图失败",
	ERROR_CHECK_EXIST_INDEX_BANNER_FAIL:       "验证已存在首页轮播图失败",
	ERROR_COUNT_INDEX_BANNER_FAIL:             "统计首页轮播图数量失败",

	ERROR_EDIT_HOT_SEARCH_FAIL:              "编辑热搜词失败",
	ERROR_NOT_EXIST_HOT_SEARCH:              "热搜词不存在",
	ERROR_GET_HOT_SEARCH_FAIL:               "获取热搜词失败",
	ERROR_GET_ALL_HOT_SEARCH_FAIL:           "获取所有热搜词失败",
	ERROR_CLEAN_SOFT_DELETE_HOT_SEARCH_FAIL: "清空所有软删除热搜词失败",
	ERROR_ADD_HOT_SEARCH_FAIL:               "添加热搜词失败",
	ERROR_DELETE_HOT_SEARCH_FAIL:            "删除热搜词失败",
	ERROR_CHECK_EXIST_HOT_SEARCH_FAIL:       "验证已存在热搜词失败",
	ERROR_COUNT_HOT_SEARCH_FAIL:             "统计热搜词数量失败",

	ERROR_EDIT_ORDER_INFO_FAIL:              "编辑订单信息失败",
	ERROR_NOT_EXIST_ORDER_INFO:              "订单信息不存在",
	ERROR_GET_ORDER_INFO_FAIL:               "获取订单信息失败",
	ERROR_GET_ALL_ORDER_INFO_FAIL:           "获取所有订单信息失败",
	ERROR_CLEAN_SOFT_DELETE_ORDER_INFO_FAIL: "清空所有软删除订单信息失败",
	ERROR_ADD_ORDER_INFO_FAIL:               "添加订单信息失败",
	ERROR_DELETE_ORDER_INFO_FAIL:            "删除订单信息失败",
	ERROR_CHECK_EXIST_ORDER_INFO_FAIL:       "验证已存在订单信息失败",
	ERROR_COUNT_ORDER_INFO_FAIL:             "统计订单信息数量失败",

	ERROR_EDIT_ORDER_PRODUCT_FAIL:              "编辑订单商品失败",
	ERROR_NOT_EXIST_ORDER_PRODUCT:              "订单商品不存在",
	ERROR_GET_ORDER_PRODUCT_FAIL:               "获取订单商品失败",
	ERROR_GET_ALL_ORDER_PRODUCT_FAIL:           "获取所有订单商品失败",
	ERROR_CLEAN_SOFT_DELETE_ORDER_PRODUCT_FAIL: "清空所有软删除订单商品失败",
	ERROR_ADD_ORDER_PRODUCT_FAIL:               "添加订单商品失败",
	ERROR_DELETE_ORDER_PRODUCT_FAIL:            "删除订单商品失败",
	ERROR_CHECK_EXIST_ORDER_PRODUCT_FAIL:       "验证已存在订单商品失败",
	ERROR_COUNT_ORDER_PRODUCT_FAIL:             "统计订单商品数量失败",

	ERROR_EDIT_ADDRESS_FAIL:              "编辑用户收货地址失败",
	ERROR_NOT_EXIST_ADDRESS:              "用户收货地址不存在",
	ERROR_GET_ADDRESS_FAIL:               "获取用户收货地址失败",
	ERROR_GET_ALL_ADDRESS_FAIL:           "获取所有用户收货地址失败",
	ERROR_CLEAN_SOFT_DELETE_ADDRESS_FAIL: "清空所有软删除用户收货地址失败",
	ERROR_ADD_ADDRESS_FAIL:               "添加用户收货地址失败",
	ERROR_DELETE_ADDRESS_FAIL:            "删除用户收货地址失败",
	ERROR_CHECK_EXIST_ADDRESS_FAIL:       "验证已存在用户收货地址失败",
	ERROR_COUNT_ADDRESS_FAIL:             "统计用户收货地址数量失败",

	ERROR_EDIT_COLLECT_FAIL:              "编辑用户收藏失败",
	ERROR_NOT_EXIST_COLLECT:              "用户收藏不存在",
	ERROR_GET_COLLECT_FAIL:               "获取用户收藏失败",
	ERROR_GET_ALL_COLLECT_FAIL:           "获取所有用户收藏失败",
	ERROR_CLEAN_SOFT_DELETE_COLLECT_FAIL: "清空所有软删除用户收藏失败",
	ERROR_ADD_COLLECT_FAIL:               "添加用户收藏失败",
	ERROR_DELETE_COLLECT_FAIL:            "删除用户收藏失败",
	ERROR_CHECK_EXIST_COLLECT_FAIL:       "验证已存在用户收藏失败",
	ERROR_COUNT_COLLECT_FAIL:             "统计用户收藏数量失败",

	ERROR_EDIT_LEAVING_MESSAGE_FAIL:              "编辑用户留言失败",
	ERROR_NOT_EXIST_LEAVING_MESSAGE:              "用户留言不存在",
	ERROR_GET_LEAVING_MESSAGE_FAIL:               "获取用户留言失败",
	ERROR_GET_ALL_LEAVING_MESSAGE_FAIL:           "获取所有用户留言失败",
	ERROR_CLEAN_SOFT_DELETE_LEAVING_MESSAGE_FAIL: "清空所有软删除用户留言失败",
	ERROR_ADD_LEAVING_MESSAGE_FAIL:               "添加用户留言失败",
	ERROR_DELETE_LEAVING_MESSAGE_FAIL:            "删除用户留言失败",
	ERROR_CHECK_EXIST_LEAVING_MESSAGE_FAIL:       "验证已存在用户留言失败",
	ERROR_COUNT_LEAVING_MESSAGE_FAIL:             "统计用户留言数量失败",

	ERROR_EDIT_SHOPPING_CART_FAIL:              "编辑购物车失败",
	ERROR_NOT_EXIST_SHOPPING_CART:              "购物车不存在",
	ERROR_GET_SHOPPING_CART_FAIL:               "获取购物车失败",
	ERROR_GET_ALL_SHOPPING_CART_FAIL:           "获取所有购物车失败",
	ERROR_CLEAN_SOFT_DELETE_SHOPPING_CART_FAIL: "清空所有软删除购物车失败",
	ERROR_ADD_SHOPPING_CART_FAIL:               "添加购物车失败",
	ERROR_DELETE_SHOPPING_CART_FAIL:            "删除购物车失败",
	ERROR_CHECK_EXIST_SHOPPING_CART_FAIL:       "验证已存在购物车失败",
	ERROR_COUNT_SHOPPING_CART_FAIL:             "统计购物车数量失败",
}

// GetMsg get error information based on Code
func GetMsg(code int) string {
	msg, ok := MsgFlags[code]
	if ok {
		return msg
	}

	return MsgFlags[ERROR]
}
